package com.lynn9388.datamonitor.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lynn9388.datamonitor.dao.MobileData;
import com.lynn9388.datamonitor.dao.WifiData;

import com.lynn9388.datamonitor.dao.MobileDataDao;
import com.lynn9388.datamonitor.dao.WifiDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mobileDataDaoConfig;
    private final DaoConfig wifiDataDaoConfig;

    private final MobileDataDao mobileDataDao;
    private final WifiDataDao wifiDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mobileDataDaoConfig = daoConfigMap.get(MobileDataDao.class).clone();
        mobileDataDaoConfig.initIdentityScope(type);

        wifiDataDaoConfig = daoConfigMap.get(WifiDataDao.class).clone();
        wifiDataDaoConfig.initIdentityScope(type);

        mobileDataDao = new MobileDataDao(mobileDataDaoConfig, this);
        wifiDataDao = new WifiDataDao(wifiDataDaoConfig, this);

        registerDao(MobileData.class, mobileDataDao);
        registerDao(WifiData.class, wifiDataDao);
    }
    
    public void clear() {
        mobileDataDaoConfig.getIdentityScope().clear();
        wifiDataDaoConfig.getIdentityScope().clear();
    }

    public MobileDataDao getMobileDataDao() {
        return mobileDataDao;
    }

    public WifiDataDao getWifiDataDao() {
        return wifiDataDao;
    }

}
