package com.lynn9388.datamonitor.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lynn9388.datamonitor.dao.TrafficLog;

import com.lynn9388.datamonitor.dao.TrafficLogDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trafficLogDaoConfig;

    private final TrafficLogDao trafficLogDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trafficLogDaoConfig = daoConfigMap.get(TrafficLogDao.class).clone();
        trafficLogDaoConfig.initIdentityScope(type);

        trafficLogDao = new TrafficLogDao(trafficLogDaoConfig, this);

        registerDao(TrafficLog.class, trafficLogDao);
    }
    
    public void clear() {
        trafficLogDaoConfig.getIdentityScope().clear();
    }

    public TrafficLogDao getTrafficLogDao() {
        return trafficLogDao;
    }

}
