package com.lynn9388.datamonitor.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lynn9388.datamonitor.dao.TrafficLog;
import com.lynn9388.datamonitor.dao.App;
import com.lynn9388.datamonitor.dao.AppLog;

import com.lynn9388.datamonitor.dao.TrafficLogDao;
import com.lynn9388.datamonitor.dao.AppDao;
import com.lynn9388.datamonitor.dao.AppLogDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trafficLogDaoConfig;
    private final DaoConfig appDaoConfig;
    private final DaoConfig appLogDaoConfig;

    private final TrafficLogDao trafficLogDao;
    private final AppDao appDao;
    private final AppLogDao appLogDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trafficLogDaoConfig = daoConfigMap.get(TrafficLogDao.class).clone();
        trafficLogDaoConfig.initIdentityScope(type);

        appDaoConfig = daoConfigMap.get(AppDao.class).clone();
        appDaoConfig.initIdentityScope(type);

        appLogDaoConfig = daoConfigMap.get(AppLogDao.class).clone();
        appLogDaoConfig.initIdentityScope(type);

        trafficLogDao = new TrafficLogDao(trafficLogDaoConfig, this);
        appDao = new AppDao(appDaoConfig, this);
        appLogDao = new AppLogDao(appLogDaoConfig, this);

        registerDao(TrafficLog.class, trafficLogDao);
        registerDao(App.class, appDao);
        registerDao(AppLog.class, appLogDao);
    }
    
    public void clear() {
        trafficLogDaoConfig.getIdentityScope().clear();
        appDaoConfig.getIdentityScope().clear();
        appLogDaoConfig.getIdentityScope().clear();
    }

    public TrafficLogDao getTrafficLogDao() {
        return trafficLogDao;
    }

    public AppDao getAppDao() {
        return appDao;
    }

    public AppLogDao getAppLogDao() {
        return appLogDao;
    }

}
