package com.lynn9388.datamonitor.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRAFFIC_LOG".
 */
public class TrafficLog {

    private Long id;
    /** Not-null value. */
    private java.util.Date time;
    private long sendBytes;
    private long receiveBytes;
    /**
     * Not-null value.
     */
    private String networkType;

    public TrafficLog() {
    }

    public TrafficLog(Long id) {
        this.id = id;
    }

    public TrafficLog(Long id, java.util.Date time, long sendBytes, long receiveBytes, String networkType) {
        this.id = id;
        this.time = time;
        this.sendBytes = sendBytes;
        this.receiveBytes = receiveBytes;
        this.networkType = networkType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public long getSendBytes() {
        return sendBytes;
    }

    public void setSendBytes(long sendBytes) {
        this.sendBytes = sendBytes;
    }

    public long getReceiveBytes() {
        return receiveBytes;
    }

    public void setReceiveBytes(long receiveBytes) {
        this.receiveBytes = receiveBytes;
    }

    /** Not-null value. */
    public String getNetworkType() {
        return networkType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNetworkType(String networkType) {
        this.networkType = networkType;
    }

}
