package com.lynn9388.datamonitor.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRAFFIC_LOG".
 */
public class TrafficLog {

    private Long id;
    /** Not-null value. */
    private java.util.Date time;
    private long mobileRxBytes;
    private long mobileTxBytes;
    private long wifiRxBytes;
    private long wifiTxBytes;
    private long totalRxBytes;
    private long totalTxBytes;

    public TrafficLog() {
    }

    public TrafficLog(Long id) {
        this.id = id;
    }

    public TrafficLog(Long id, java.util.Date time, long mobileRxBytes, long mobileTxBytes, long wifiRxBytes, long wifiTxBytes, long totalRxBytes, long totalTxBytes) {
        this.id = id;
        this.time = time;
        this.mobileRxBytes = mobileRxBytes;
        this.mobileTxBytes = mobileTxBytes;
        this.wifiRxBytes = wifiRxBytes;
        this.wifiTxBytes = wifiTxBytes;
        this.totalRxBytes = totalRxBytes;
        this.totalTxBytes = totalTxBytes;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public long getMobileRxBytes() {
        return mobileRxBytes;
    }

    public void setMobileRxBytes(long mobileRxBytes) {
        this.mobileRxBytes = mobileRxBytes;
    }

    public long getMobileTxBytes() {
        return mobileTxBytes;
    }

    public void setMobileTxBytes(long mobileTxBytes) {
        this.mobileTxBytes = mobileTxBytes;
    }

    public long getWifiRxBytes() {
        return wifiRxBytes;
    }

    public void setWifiRxBytes(long wifiRxBytes) {
        this.wifiRxBytes = wifiRxBytes;
    }

    public long getWifiTxBytes() {
        return wifiTxBytes;
    }

    public void setWifiTxBytes(long wifiTxBytes) {
        this.wifiTxBytes = wifiTxBytes;
    }

    public long getTotalRxBytes() {
        return totalRxBytes;
    }

    public void setTotalRxBytes(long totalRxBytes) {
        this.totalRxBytes = totalRxBytes;
    }

    public long getTotalTxBytes() {
        return totalTxBytes;
    }

    public void setTotalTxBytes(long totalTxBytes) {
        this.totalTxBytes = totalTxBytes;
    }

}
