package com.lynn9388.datamonitor.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WIFI_DATA".
 */
public class WifiData {

    private Long id;
    /** Not-null value. */
    private java.util.Date startTime;
    private long receivedBytes;
    private long transmittedBytes;

    public WifiData() {
    }

    public WifiData(Long id) {
        this.id = id;
    }

    public WifiData(Long id, java.util.Date startTime, long receivedBytes, long transmittedBytes) {
        this.id = id;
        this.startTime = startTime;
        this.receivedBytes = receivedBytes;
        this.transmittedBytes = transmittedBytes;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getStartTime() {
        return startTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public long getReceivedBytes() {
        return receivedBytes;
    }

    public void setReceivedBytes(long receivedBytes) {
        this.receivedBytes = receivedBytes;
    }

    public long getTransmittedBytes() {
        return transmittedBytes;
    }

    public void setTransmittedBytes(long transmittedBytes) {
        this.transmittedBytes = transmittedBytes;
    }

}
